[package]
name = "comprs"
version = "0.1.0"
authors = ["flauntingspade4 <48335751+flauntingspade4@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde = {version = "1.0.117", features = ["macros"], optional = true}

[features]
default = ["serde"]