[package]
name = "huffman-comprs-cli"
version = "0.1.0"
authors = ["flauntingspade4 <48335751+flauntingspade4@users.noreply.github.com>"]
edition = "2018"

[dependencies]
bincode = "*"
clap = "2.33.3"
huffman-comprs = {path = "../huffman-comprs"}
